### ISSUE TITLE
Show available datasets for a given project

### ISSUE THREAD

**Issue by stephenplaza** [neuroglancerhub/ng_workspaces#59]
Provide the ability for a user to select a dataset based on querying a the appropriate cloud function (must be logged into google)

Requirements:

* add ability to login into a Google account
* allow user to specify the appropriate Google project in settings (cache these settings)
* fetch dataset information by calling a cloud function
* display this dataset information at the top of neurohub for relevant workflows as a drop-down
* refresh screen on dataset change

**Comment by neomorphic** [comment]
Changes merged into main branch at a11a380f
